version: '3.4'
name: 'e-shop'
services:
  catalogdb:
    image: postgres:14.8-alpine
  basketdb:
    image: postgres:14.8-alpine
  distributedcache:
    image: redis
  orderdb:
    image: mcr.microsoft.com/mssql/server
volumes:
  postgres_catalog:
  postgres_basket:
