version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - '5433:5432'
    volumes: 
      - postgres_catalog:/var/lib/postgresql/data/ 
  basketdb:
    container_name: basketdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5434:5432'
    volumes:
      - postgres_basket:/var/lib/postgresql/data/ 
  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=hKn12345678
    restart: always
    ports:
      - "1434:1433"
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6380:6379"