version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    platform: linux/arm64/v8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - '5433:5432'
    volumes: 
      - postgres_catalog:/var/lib/postgresql/data/ 
  basketdb:
    container_name: basketdb
    platform: linux/arm64/v8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5434:5432'
    volumes:
      - postgres_basket:/var/lib/postgresql/data/ 