version: '3.4'
name: 'e-shop'
services:
  catalogdb:
    image: postgres:14.8-alpine
  basketdb:
    image: postgres:14.8-alpine
  distributedcache:
    image: redis  
volumes:
  postgres_catalog:
  postgres_basket:
